# Generated by Django 5.1.15 on 2026-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
